import { Country } from '../../../Shared/Types/Index';

export type ConstructorAnalytics = {
    id: string,
    country: null|Country,
    name: string,
    position: number,
    points: number,
    wins: number,
};

export type DriverAnalytics = {
    id: string,
    country: null|Country,
    name: string,
    short_code: string,
    position: number,
    points: number,
    avg_finish_position: number,
    class_wins: number,
    fastest_laps: number,
    final_appearances: number,
    hat_tricks: number,
    podiums: number,
    poles: number,
    races_led: number,
    rallies_led: number,
    retirements: number,
    semi_final_appearances: number,
    stage_wins: number,
    starts: number,
    top10s: number,
    top5s: number,
    wins: number,
    wins_percentage: number,
};

export type TeamAnalytics = {
    id: string,
    country: null|Country,
    name: string,
    position: number,
    points: number,
    class_wins: number,
    fastest_laps: number,
    final_appearances: number,
    finishes_one_and_two: number,
    podiums: number,
    poles: number,
    qualifies_one_and_two: number,
    races_led: number,
    rallies_led: number,
    retirements: number,
    semi_final_appearances: number,
    stage_wins: number,
    starts: number,
    top10s: number,
    top5s: number,
    wins: number,
    wins_percentage: number,
};
