services:
  _defaults:
    autoconfigure: true
    autowire: true

  Kishlin\Backend\Country\:
    resource: '../../../'
    exclude:
      - '../../../Application/*/*Exception.php'
      - '../../../Infrastructure/Persistence/Fixtures'
      - '../../../Infrastructure/Persistence/Doctrine/DbalTypes'
      - '../../../Domain/{DomainEvent,Entity,ReadModel,ValueObject,View}'

  _instanceof:

    Kishlin\Backend\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['kishlin.application_service']

    Kishlin\Backend\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['kishlin.application_service']

    Kishlin\Backend\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['kishlin.application_service']
