version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/kishlin/MotorsportTracker

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - nilnil
    - nilerr
    - revive
    - unparam
  settings:
    revive:
      confidence: 0.8
    staticcheck:
      checks:
        - "all"
        - "-ST1000" # missing package comment
        - "-S1002" # comparison with boolean prevention
  exclusions:
    paths:
      - "^apps/Admin/.*"  # Exclude Admin app directory
      - "^apps/MotorsportTracker/.*"  # Exclude MotorsportTracker app directory
      - "^docs/.*"  # Exclude documentation directory
      - "^etc/.*"  # Exclude etc directory
      - "^features/.*"  # Exclude vendor directory
      - "^src/Backend/.*"  # Exclude Backend source directory
      - "^tests/.*"  # Exclude etc directory
      - "^vendor/.*"  # Exclude vendor directory
      - ".*\\.pb\\.go$"  # Exclude generated protobuf files
      - ".*\\.gen\\.go$"  # Exclude generated code files

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
