default:
  suites:
    use_case_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Backend\UseCaseTests\Context\Country\CountryContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Championship\ChampionshipCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Championship\SeasonCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Car\DriverMoveRecordingContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Driver\DriverCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Car\CarRegistrationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Venue\VenueCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Team\TeamCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Event\StepTypeContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Racer\RacerContext
    api_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Apps\MotorsportTracker\Backend\ApiTests\Context\Context
      filters:
        tags: '@api'
    backoffice_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Apps\Backoffice\BackofficeTests\Context\Context
      filters:
        tags: '@backoffice'
