default:
  suites:
    use_case_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Championship\ChampionshipCreationContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\MotorsportTracker\Championship\SeasonCreationContext
    api_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Apps\MotorsportTracker\Backend\ApiTests\Context\Context
      filters:
        tags: '@api'
    backoffice_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Apps\Backoffice\BackofficeTests\Context\Context
      filters:
        tags: '@backoffice'
