events:
  resource: ../../src/MotorsportTracker/Event/Controller/
  prefix: /api/v1/events
  type: annotation
  stateless: true

standings:
  resource: ../../src/MotorsportTracker/Standing/Controller/
  prefix: /api/v1/standings
  type: annotation
  stateless: true
