calendar:
  resource: ../../src/MotorsportCache/Calendar/Controller/
  prefix: /api/v1/calendar
  type: annotation
  stateless: true

results:
  resource: ../../src/MotorsportCache/Results/Controller/
  prefix: /api/v1/results
  type: annotation
  stateless: true

schedule:
  resource: ../../src/MotorsportCache/Schedule/Controller/
  prefix: /api/v1/schedule
  type: annotation
  stateless: true

season:
  resource: ../../src/MotorsportCache/Season/Controller/
  prefix: /api/v1/season
  type: annotation
  stateless: true

standings:
  resource: ../../src/MotorsportTracker/Standing/Controller/
  prefix: /api/v1/standings
  type: annotation
  stateless: true
