calendar:
  resource: ../../src/MotorsportCache/Calendar/Controller/
  prefix: /api/v1/calendar
  type: annotation
  stateless: true

events:
  resource: ../../src/MotorsportCache/Event/Controller/
  prefix: /api/v1/events
  type: annotation
  stateless: true

results:
  resource: ../../src/MotorsportCache/Results/Controller/
  prefix: /api/v1/results
  type: annotation
  stateless: true

event_graphs:
  resource: ../../src/MotorsportCache/EventGraph/Controller/
  prefix: /api/v1/graph/event
  type: annotation
  stateless: true

schedule:
  resource: ../../src/MotorsportCache/Schedule/Controller/
  prefix: /api/v1/schedule
  type: annotation
  stateless: true

standings:
  resource: ../../src/MotorsportCache/Standings/Controller/
  prefix: /api/v1/standings
  type: annotation
  stateless: true
