calendar:
  resource: ../../src/MotorsportCache/Calendar/Controller/
  prefix: /api/v1/calendar
  type: annotation
  stateless: true

standings:
  resource: ../../src/MotorsportTracker/Standing/Controller/
  prefix: /api/v1/standings
  type: annotation
  stateless: true
