import { ChampionshipList } from '../Shared/Types';

const CHAMPIONSHIPS: ChampionshipList = {
    '24-hours-of-daytona': {
        name: '24h Of Daytona',
        displayName: '24h of Daytona',
        shortName: '24h Daytona',
        slug: '24-hours-of-daytona',
        years: Array.from({ length: 63 }, (x, i) => 1962 + i),
        isMultiDriver: true,
        menuIconFormat: null,
    },
    '24-hours-of-le-mans': {
        name: '24h Of Le Mans',
        displayName: '24h of Le Mans',
        shortName: '24h Le Mans',
        slug: '24-hours-of-le-mans',
        years: Array.from({ length: 102 }, (x, i) => 1923 + i),
        isMultiDriver: true,
        menuIconFormat: null,
    },
    'adac-24h-rennen-nurburgring': {
        name: 'ADAC 24h Rennen Nürburgring',
        displayName: '24h Nürburgring',
        shortName: '24h Nürburgring',
        slug: 'adac-24h-rennen-nürburgring',
        years: Array.from({ length: 3 }, (x, i) => 2022 + i),
        isMultiDriver: true,
        menuIconFormat: null,
    },
    'fia-formula-one-world-championship': {
        name: 'Formula One',
        displayName: 'Formula One',
        shortName: 'Formula 1',
        slug: 'fia-formula-one-world-championship',
        years: Array.from({ length: 75 }, (x, i) => 1950 + i),
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'fia-formula-2-championship': {
        name: 'FIA Formula 2 Championship',
        displayName: 'Formula 2',
        shortName: 'Formula 2',
        slug: 'fia-formula-2-championship',
        years: Array.from({ length: 8 }, (x, i) => 2017 + i),
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'fia-formula-3-championship': {
        name: 'FIA Formula 3 Championship',
        displayName: 'Formula 3',
        shortName: 'Formula 3',
        slug: 'fia-formula-3-championship',
        years: Array.from({ length: 6 }, (x, i) => 2019 + i),
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'abb-fia-formula-e-world-championship': {
        name: 'Formula E',
        displayName: 'Formula E',
        shortName: 'Formula E',
        slug: 'abb-fia-formula-e-world-championship',
        years: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2022, 2023], // No championship in 2021
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'f4-french-championship': {
        name: 'F4 France',
        displayName: 'F4 France',
        shortName: 'F4 France',
        slug: 'f4-french-championship',
        years: Array.from({ length: 3 }, (x, i) => 2021 + i),
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'w-series': {
        name: 'W Series',
        displayName: 'W Series',
        shortName: 'W Series',
        slug: 'w-series',
        years: [2019, 2021, 2022], // No championship in 2020
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
    'fia-world-endurance-championship': {
        name: 'World Endurance Championship',
        displayName: 'World Endurance Championship',
        shortName: 'WEC',
        slug: 'fia-world-endurance-championship',
        years: Array.from({ length: 12 }, (x, i) => 2012 + i),
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'gt-world-challenge-europe-endurance': {
        name: 'GT World Challenge Europe',
        displayName: 'GT World Europe Endurance',
        shortName: 'GT Europe E',
        slug: 'gt-world-challenge-europe-endurance',
        years: Array.from({ length: 11 }, (x, i) => 2013 + i),
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'gt-world-challenge-europe-sprint-cup': {
        name: 'GT World Challenge Europe Sprint Cup',
        displayName: 'GT World Europe Sprint',
        shortName: 'GT Europe S',
        slug: 'gt-world-challenge-europe-sprint-cup',
        years: Array.from({ length: 5 }, (x, i) => 2019 + i),
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'ffsa-gt4-france': {
        name: 'GT4 France',
        displayName: 'GT4 France',
        shortName: 'GT4 France',
        slug: 'ffsa-gt4-france',
        years: Array.from({ length: 2 }, (x, i) => 2022 + i),
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'imsa-sportscar-championship': {
        name: 'IMSA SportsCar Championship',
        displayName: 'IMSA SportsCar Championship',
        shortName: 'IMSA',
        slug: 'imsa-sportscar-championship',
        years: Array.from({ length: 11 }, (x, i) => 2014 + i),
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'adac-gt-masters': {
        name: 'ADAC GT Masters',
        displayName: 'ADAC GT Masters',
        shortName: 'ADAC',
        slug: 'adac-gt-masters',
        years: [2021, 2022, 2023],
        isMultiDriver: true,
        menuIconFormat: 'svg',
    },
    'fim-motogp-world-championship': {
        name: 'MotoGP',
        displayName: 'MotoGP',
        shortName: 'MotoGP',
        slug: 'fim-motogp-world-championship',
        years: Array.from({ length: 76 }, (x, i) => 1949 + i),
        isMultiDriver: false,
        menuIconFormat: 'svg',
    },
};

export default CHAMPIONSHIPS;
