services:
  _defaults:
    autoconfigure: true
    autowire: true

  Kishlin\Backend\MotorsportTracker\:
    resource: '../../../../'
    exclude:
      - '../../../../*/Application/*/*Exception.php'
      - '../../../../*/Infrastructure/Persistence/Doctrine/DbalTypes'
      - '../../../../*/Domain/{DomainEvent,Entity,ReadModel,ValueObject,View}'

  _instanceof:

    Kishlin\Backend\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: ['kishlin.application_service']

    Kishlin\Backend\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['kishlin.application_service']

    Kishlin\Backend\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['kishlin.application_service']


##> Persistence

  Doctrine\ORM\EntityManagerInterface:
    factory: [ Kishlin\Backend\MotorsportTracker\Shared\Infrastructure\Persistence\Doctrine\EntityManagerFactory\MotorsportTrackerEntityManagerFactory, create ]
    arguments:
        $parameters:
          url: '%kishlin.database.url%'
        $environment: '%kishlin.app.environment%'
    public: true

  kishlin.app.infrastructure.entity_manager: '@Doctrine\ORM\EntityManagerInterface'
