CREATE TABLE IF NOT EXISTS seasons (
    id SERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL,
    series SERIAL NOT NULL REFERENCES series(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    end_year INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
