framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true

  #esi: true
  #fragments: true
  php_errors:
    log: true

  messenger:
    default_bus: symfony.messenger.bus.command
    buses:
      symfony.messenger.bus.command: ~
      symfony.messenger.bus.event: ~
      symfony.messenger.bus.query: ~

  cache:
    default_memcached_provider: 'memcached://%kishlin.memcached%'
    pools:
      app.cache.memcached:
        adapter: cache.adapter.memcached
        public: false
        default_lifetime: 31536000

when@test:
  framework:
    test: true
